spring:
  application:
    name: your-turn-games-catalog
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/games_catalog
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  mvc:
    problemdetails:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

logging:
  include-application-name: false